python:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.py'

javascript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.mjs'
      - '**/*.cjs'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/labeler.yml'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*.md'

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - '*.toml'
      - '*.json'
      - '*.env*'
      - '.gitignore'
